# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-05 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
