# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180505_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pomodoro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pomodoro_timer', models.IntegerField(default=25, help_text='Set pomodoro timer, defaults to 25 minutes')),
                ('break_timer', models.IntegerField(default=5, help_text='Set break time, defaults to 5 minutes until 4 pomodoros.')),
                ('big_break_timer', models.IntegerField(default=15, help_text='Set break time after 4 pomodoros are finished, defaults to 15 minutes')),
            ],
        ),
    ]
