# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pomodoro'),
    ]

    operations = [
        migrations.CreateModel(
            name='PomodoroTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pomodoro_count', models.IntegerField(default=0, help_text='Count of completed Pomodoros.')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Task')),
            ],
        ),
    ]
