# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pomodorotask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomodorotask',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_pomodoro', to='api.Task'),
        ),
    ]
