# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180506_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pomodorotask',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='pomodoro_count',
            field=models.IntegerField(default=0, help_text='Count of finished pomodoros by this task.'),
        ),
        migrations.DeleteModel(
            name='PomodoroTask',
        ),
    ]
